In [1]:
import numpy as np
import pandas as pd

# 更新交易日

In [2]:
update_start = '20260401'; update_end = '20260430'

In [3]:
old_calendar = pd.read_pickle('./data/calendar.pkl')
new_calendar = pd.read_pickle('./data_update/calendar.pkl')
calendar = pd.concat([old_calendar, new_calendar]).reset_index(drop=True)
calendar.to_pickle('./data/calendar.pkl')

# 更新上市天数

In [4]:
old_listdays = pd.read_pickle('./data/listdays.pkl')
new_listdays = pd.read_pickle('./data_update/listdays.pkl')
listdays = pd.concat([old_listdays, new_listdays]).fillna(0).astype(int)
listdays.to_pickle('./data/listdays.pkl')

# 更新st状态

In [5]:
old_is_st = pd.read_pickle('./data/is_st.pkl')
is_st = pd.read_pickle('./data_update/is_st.pkl')
old_is_st = old_is_st.reindex(columns=listdays.columns, fill_value=False)
is_st = pd.concat([old_is_st, is_st], axis=0)
is_st.to_pickle('./data/is_st.pkl')
is_st

code,000004.SZ,000005.SZ,600652.SH,600656.SH,600602.SH,600601.SH,600654.SH,600651.SH,600653.SH,000002.SZ,...,603293.SH,301513.SZ,920191.BJ,688820.SH,001312.SZ,688808.SH,920125.BJ,920156.BJ,920186.BJ,301599.SZ
20140102,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20140103,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20140106,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20140107,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20140108,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20260424,True,True,True,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20260427,True,True,True,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20260428,True,True,True,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20260429,True,True,True,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20260430,True,True,True,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

# 更新日频行情

In [6]:
data = pd.read_pickle('./data_update/kline.pkl')

In [7]:
close = data.pivot(index='trade_date', columns='code', values='close')
old_close = pd.read_pickle('./data/close.pkl')
close = pd.concat([old_close, close], axis=0)
close = close.reindex(columns=listdays.columns)
close.to_pickle('./data/close.pkl')

adjclose = data.pivot(index='trade_date', columns='code', values='adjclose')
old_adjclose = pd.read_pickle('./data/adjclose.pkl')
adjclose = pd.concat([old_adjclose, adjclose], axis=0)
adjclose = adjclose.reindex(columns=listdays.columns)
adjclose.to_pickle('./data/adjclose.pkl')

adjopen = data.pivot(index='trade_date', columns='code', values='adjopen')
old_adjopen = pd.read_pickle('./data/adjopen.pkl')
adjopen = pd.concat([old_adjopen, adjopen], axis=0)
adjopen = adjopen.reindex(columns=listdays.columns)
adjopen.to_pickle('./data/adjopen.pkl')

adjhigh = data.pivot(index='trade_date', columns='code', values='adjhigh')
old_adjhigh = pd.read_pickle('./data/adjhigh.pkl')
adjhigh = pd.concat([old_adjhigh, adjhigh], axis=0)
adjhigh = adjhigh.reindex(columns=listdays.columns)
adjhigh.to_pickle('./data/adjhigh.pkl')

adjlow = data.pivot(index='trade_date', columns='code', values='adjlow')
old_adjlow = pd.read_pickle('./data/adjlow.pkl')
adjlow = pd.concat([old_adjlow, adjlow], axis=0)
adjlow = adjlow.reindex(columns=listdays.columns)
adjlow.to_pickle('./data/adjlow.pkl')

data['adjvwap'] = data['vwap']*data['adjfactor']
adjvwap = data.pivot(index='trade_date', columns='code', values='adjvwap')
old_adjvwap = pd.read_pickle('./data/adjvwap.pkl')
adjvwap = pd.concat([old_adjvwap, adjvwap], axis=0)
adjvwap = adjvwap.reindex(columns=listdays.columns)
adjvwap.to_pickle('./data/adjvwap.pkl')

returns = data.pivot(index='trade_date', columns='code', values='returns') / 100
old_returns = pd.read_pickle('./data/returns.pkl')
returns = pd.concat([old_returns, returns], axis=0)
returns = returns.reindex(columns=listdays.columns)
returns.to_pickle('./data/returns.pkl')

volume = data.pivot(index='trade_date', columns='code', values='volume')
old_volume = pd.read_pickle('./data/volume.pkl')
volume = pd.concat([old_volume, volume], axis=0)
volume = volume.reindex(columns=listdays.columns)
volume.to_pickle('./data/volume.pkl')

amount = data.pivot(index='trade_date', columns='code', values='amount')
old_amount = pd.read_pickle('./data/amount.pkl')
amount = pd.concat([old_amount, amount], axis=0)
amount = amount.reindex(columns=listdays.columns)
amount.to_pickle('./data/amount.pkl')

limit = data.pivot(index='trade_date', columns='code', values='limit')
old_limit = pd.read_pickle('./data/limit.pkl')
limit = pd.concat([old_limit, limit], axis=0)
limit = limit.reindex(columns=listdays.columns)
limit.to_pickle('./data/limit.pkl')

stopping = data.pivot(index='trade_date', columns='code', values='stopping')
old_stopping = pd.read_pickle('./data/stopping.pkl')
stopping = pd.concat([old_stopping, stopping], axis=0)
stopping = stopping.reindex(columns=listdays.columns)
stopping.to_pickle('./data/stopping.pkl')

# 更新总市值（换手率）

In [8]:
old_cap = pd.read_pickle('./data/cap.pkl')
cap = pd.read_pickle('./data_update/cap.pkl')
cap = pd.concat([old_cap, cap], axis=0)
cap = cap.reindex(columns=listdays.columns)
cap.to_pickle('./data/cap.pkl')
cap

code,000004.SZ,000005.SZ,600652.SH,600656.SH,600602.SH,600601.SH,600654.SH,600651.SH,600653.SH,000002.SZ,...,603293.SH,301513.SZ,920191.BJ,688820.SH,001312.SZ,688808.SH,920125.BJ,920156.BJ,920186.BJ,301599.SZ
trade_dt,,,,,,,,,,,,,,,,,,,,,
20140102,9.917646e+05,2.276691e+06,2.267000e+06,1.143966e+06,5.743753e+06,6.079849e+06,5.587319e+06,4.323532e+06,4.365951e+06,9.027693e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20140103,9.909249e+05,2.249261e+06,2.267000e+06,1.157290e+06,5.513637e+06,5.970104e+06,5.466512e+06,4.220063e+06,4.313559e+06,8.859392e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20140106,1.032913e+06,2.176114e+06,2.267000e+06,1.147772e+06,5.239127e+06,5.750615e+06,5.277752e+06,4.146156e+06,4.121458e+06,8.498117e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20140107,1.027035e+06,2.240117e+06,2.267000e+06,1.151579e+06,5.267239e+06,5.750615e+06,5.187146e+06,4.138766e+06,4.086530e+06,8.432661e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20140108,1.027035e+06,2.203544e+06,2.267000e+06,1.107800e+06,5.200952e+06,5.816462e+06,5.194697e+06,4.257016e+06,4.034139e+06,8.448629e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20260424,3.852266e+05,NaN,NaN,NaN,2.532361e+07,4.923352e+07,1.079098e+07,1.657146e+07,3.347774e+06,4.205604e+07,...,9.264360e+06,8171000.0,2249373.672,1.747655e+08,6.167000e+06,8.203067e+07,2809123.2,NaN,NaN,NaN
20260427,3.653696e+05,NaN,NaN,NaN,2.574725e+07,5.107123e+07,1.087730e+07,1.672188e+07,3.484021e+06,4.177601e+07,...,9.305551e+06,8388000.0,2213894.592,1.883265e+08,5.812333e+06,9.034667e+07,3022531.2,4227272.0,NaN,NaN
20260428,3.653696e+05,NaN,NaN,NaN,2.462689e+07,4.957542e+07,1.061832e+07,1.629568e+07,3.445093e+06,4.194980e+07,...,8.809469e+06,7603000.0,2242277.856,1.732380e+08,5.467000e+06,8.880564e+07,2897856.0,4143976.0,NaN,NaN
20260429,3.653696e+05,NaN,NaN,NaN,2.491063e+07,5.047290e+07,1.168303e+07,1.657146e+07,3.561876e+06,4.350619e+07,...,8.900806e+06,8290000.0,2252921.580,1.723066e+08,5.541667e+06,9.527467e+07,3767212.8,4592733.2,1.611194e+07,NaN
20260430,3.653696e+05,NaN,NaN,NaN,2.480497e+07,4.987458e+07,1.128017e+07,1.727342e+07,3.581340e+06,4.379974e+07,...,8.906178e+06,8201000.0,2290174.614,1.918657e+08,5.474000e+06,1.060885e+08,4897152.0,5048778.8,1.710131e+07,26931840.0

# 更新ETF日频

In [9]:
etf_kline = pd.read_pickle('./data_update/etf_kline.pkl')

In [10]:
old_universe = pd.read_pickle('./data/etf_close.pkl').columns.tolist()
new_universe = sorted(list(set(etf_kline['s_info_windcode'].unique().tolist())-set(old_universe)))
universe = old_universe+new_universe

In [11]:
new_etf_close = etf_kline.pivot(index='trade_dt', columns='s_info_windcode', values='s_dq_adjclose')
old_etf_close = pd.read_pickle('./data/etf_close.pkl')
etf_close = pd.concat([old_etf_close, new_etf_close], axis=0).reindex(columns=universe)
etf_close.to_pickle('./data/etf_close.pkl')

new_etf_open = etf_kline.pivot(index='trade_dt', columns='s_info_windcode', values='s_dq_adjopen')
old_etf_open = pd.read_pickle('./data/etf_open.pkl')
etf_open = pd.concat([old_etf_open, new_etf_open], axis=0).reindex(columns=universe)
etf_open.to_pickle('./data/etf_open.pkl')

new_etf_high = etf_kline.pivot(index='trade_dt', columns='s_info_windcode', values='s_dq_adjhigh')
old_etf_high = pd.read_pickle('./data/etf_high.pkl')
etf_high = pd.concat([old_etf_high, new_etf_high], axis=0).reindex(columns=universe)
etf_high.to_pickle('./data/etf_high.pkl')

new_etf_low = etf_kline.pivot(index='trade_dt', columns='s_info_windcode', values='s_dq_adjlow')
old_etf_low = pd.read_pickle('./data/etf_low.pkl')
etf_low = pd.concat([old_etf_low, new_etf_low], axis=0).reindex(columns=universe)
etf_low.to_pickle('./data/etf_low.pkl')

new_etf_volume = etf_kline.pivot(index='trade_dt', columns='s_info_windcode', values='s_dq_volume')
old_etf_volume = pd.read_pickle('./data/etf_volume.pkl')
etf_volume = pd.concat([old_etf_volume, new_etf_volume], axis=0).reindex(columns=universe)
etf_volume.to_pickle('./data/etf_volume.pkl')

new_etf_amount = etf_kline.pivot(index='trade_dt', columns='s_info_windcode', values='s_dq_amount')
old_etf_amount = pd.read_pickle('./data/etf_amount.pkl')
etf_amount = pd.concat([old_etf_amount, new_etf_amount], axis=0).reindex(columns=universe)
etf_amount.to_pickle('./data/etf_amount.pkl')

new_etf_trades = etf_kline.pivot(index='trade_dt', columns='s_info_windcode', values='trades_count')
old_etf_trades = pd.read_pickle('./data/etf_trades.pkl')
etf_trades = pd.concat([old_etf_trades, new_etf_trades], axis=0).reindex(columns=universe)
etf_trades.to_pickle('./data/etf_trades.pkl')

new_etf_discount = etf_kline.pivot(index='trade_dt', columns='s_info_windcode', values='discount_rate')
old_etf_discount = pd.read_pickle('./data/etf_discount.pkl')
etf_discount = pd.concat([old_etf_discount, new_etf_discount], axis=0).reindex(columns=universe)
etf_discount.to_pickle('./data/etf_discount.pkl')

new_etf_returns = etf_kline.pivot(index='trade_dt', columns='s_info_windcode', values='s_dq_pctchange')/100
old_etf_returns = pd.read_pickle('./data/etf_returns.pkl')
etf_returns = pd.concat([old_etf_returns, new_etf_returns], axis=0).reindex(columns=universe)
etf_returns.to_pickle('./data/etf_returns.pkl')

# 更新资金流

In [12]:
mf = pd.read_pickle('./data_update/mf.pkl')

In [13]:
ord = mf.pivot(index='trade_dt', columns='s_info_windcode', values='trades_count')
old_ord = pd.read_pickle('./data/ord.pkl')
ord = pd.concat([old_ord, ord], axis=0)
ord = ord.reindex(columns=listdays.columns)
ord.to_pickle('./data/ord.pkl')

ordM1 = mf.pivot(index='trade_dt', columns='s_info_windcode', values='buy_trades_med_order')
old_ordM1 = pd.read_pickle('./data/ordM1.pkl')
ordM1 = pd.concat([old_ordM1, ordM1], axis=0)
ordM1 = ordM1.reindex(columns=listdays.columns)
ordM1.to_pickle('./data/ordM1.pkl')

ordM2 = mf.pivot(index='trade_dt', columns='s_info_windcode', values='sell_trades_med_order')
old_ordM2 = pd.read_pickle('./data/ordM2.pkl')
ordM2 = pd.concat([old_ordM2, ordM2], axis=0)
ordM2 = ordM2.reindex(columns=listdays.columns)
ordM2.to_pickle('./data/ordM2.pkl')

ordS1 = mf.pivot(index='trade_dt', columns='s_info_windcode', values='buy_trades_small_order')
old_ordS1 = pd.read_pickle('./data/ordS1.pkl')
ordS1 = pd.concat([old_ordS1, ordS1], axis=0)
ordS1 = ordS1.reindex(columns=listdays.columns)
ordS1.to_pickle('./data/ordS1.pkl')

ordS2 = mf.pivot(index='trade_dt', columns='s_info_windcode', values='sell_trades_small_order')
old_ordS2 = pd.read_pickle('./data/ordS2.pkl')
ordS2 = pd.concat([old_ordS2, ordS2], axis=0)
ordS2 = ordS2.reindex(columns=listdays.columns)
ordS2.to_pickle('./data/ordS2.pkl')

volM1 = mf.pivot(index='trade_dt', columns='s_info_windcode', values='buy_volume_med_order')
old_volM1 = pd.read_pickle('./data/volM1.pkl')
volM1 = pd.concat([old_volM1, volM1], axis=0)
volM1 = volM1.reindex(columns=listdays.columns)
volM1.to_pickle('./data/volM1.pkl')

volM2 = mf.pivot(index='trade_dt', columns='s_info_windcode', values='sell_volume_med_order')
old_volM2 = pd.read_pickle('./data/volM2.pkl')
volM2 = pd.concat([old_volM2, volM2], axis=0)
volM2 = volM2.reindex(columns=listdays.columns)
volM2.to_pickle('./data/volM2.pkl')

volS1 = mf.pivot(index='trade_dt', columns='s_info_windcode', values='buy_volume_small_order')
old_volS1 = pd.read_pickle('./data/volS1.pkl')
volS1 = pd.concat([old_volS1, volS1], axis=0)
volS1 = volS1.reindex(columns=listdays.columns)
volS1.to_pickle('./data/volS1.pkl')

volS2 = mf.pivot(index='trade_dt', columns='s_info_windcode', values='sell_volume_small_order')
old_volS2 = pd.read_pickle('./data/volS2.pkl')
volS2 = pd.concat([old_volS2, volS2], axis=0)
volS2 = volS2.reindex(columns=listdays.columns)
volS2.to_pickle('./data/volS2.pkl')

ordL1 = mf.pivot(index='trade_dt', columns='s_info_windcode', values='buy_trades_large_order')
old_ordL1 = pd.read_pickle('./data/ordL1.pkl')
ordL1 = pd.concat([old_ordL1, ordL1], axis=0)
ordL1 = ordL1.reindex(columns=listdays.columns)
ordL1.to_pickle('./data/ordL1.pkl')

ordL2 = mf.pivot(index='trade_dt', columns='s_info_windcode', values='sell_trades_large_order')
old_ordL2 = pd.read_pickle('./data/ordL2.pkl')
ordL2 = pd.concat([old_ordL2, ordL2], axis=0)
ordL2 = ordL2.reindex(columns=listdays.columns)
ordL2.to_pickle('./data/ordL2.pkl')

volL1 = mf.pivot(index='trade_dt', columns='s_info_windcode', values='buy_volume_large_order')
old_volL1 = pd.read_pickle('./data/volL1.pkl')
volL1 = pd.concat([old_volL1, volL1], axis=0)
volL1 = volL1.reindex(columns=listdays.columns)
volL1.to_pickle('./data/volL1.pkl')

volL2 = mf.pivot(index='trade_dt', columns='s_info_windcode', values='sell_volume_large_order')
old_volL2 = pd.read_pickle('./data/volL2.pkl')
volL2 = pd.concat([old_volL2, volL2], axis=0)
volL2 = volL2.reindex(columns=listdays.columns)
volL2.to_pickle('./data/volL2.pkl')

In [14]:
volNetOpen = mf.pivot(index='trade_dt', columns='s_info_windcode', values='s_mfd_inflow_openvolume')
old_volNetOpen = pd.read_pickle('./data/volNetOpen.pkl')
volNetOpen = pd.concat([old_volNetOpen, volNetOpen], axis=0)
volNetOpen = volNetOpen.reindex(columns=listdays.columns)
volNetOpen.to_pickle('./data/volNetOpen.pkl')

volNetClose = mf.pivot(index='trade_dt', columns='s_info_windcode', values='s_mfd_inflow_closevolume')
old_volNetClose = pd.read_pickle('./data/volNetClose.pkl')
volNetClose = pd.concat([old_volNetClose, volNetClose], axis=0)
volNetClose = volNetClose.reindex(columns=listdays.columns)
volNetClose.to_pickle('./data/volNetClose.pkl')

volS1a = mf.pivot(index='trade_dt', columns='s_info_windcode', values='buy_volume_small_order_act')
old_volS1a = pd.read_pickle('./data/volS1a.pkl')
volS1a = pd.concat([old_volS1a, volS1a], axis=0)
volS1a = volS1a.reindex(columns=listdays.columns)
volS1a.to_pickle('./data/volS1a.pkl')

volS2a = mf.pivot(index='trade_dt', columns='s_info_windcode', values='sell_volume_small_order_act')
old_volS2a = pd.read_pickle('./data/volS2a.pkl')
volS2a = pd.concat([old_volS2a, volS2a], axis=0)
volS2a = volS2a.reindex(columns=listdays.columns)
volS2a.to_pickle('./data/volS2a.pkl')

volM1a = mf.pivot(index='trade_dt', columns='s_info_windcode', values='buy_volume_med_order_act')
old_volM1a = pd.read_pickle('./data/volM1a.pkl')
volM1a = pd.concat([old_volM1a, volM1a], axis=0)
volM1a = volM1a.reindex(columns=listdays.columns)
volM1a.to_pickle('./data/volM1a.pkl')

volM2a = mf.pivot(index='trade_dt', columns='s_info_windcode', values='sell_volume_med_order_act')
old_volM2a = pd.read_pickle('./data/volM2a.pkl')
volM2a = pd.concat([old_volM2a, volM2a], axis=0)
volM2a = volM2a.reindex(columns=listdays.columns)
volM2a.to_pickle('./data/volM2a.pkl')

volL1a = mf.pivot(index='trade_dt', columns='s_info_windcode', values='buy_volume_large_order_act')
old_volL1a = pd.read_pickle('./data/volL1a.pkl')
volL1a = pd.concat([old_volL1a, volL1a], axis=0)
volL1a = volL1a.reindex(columns=listdays.columns)
volL1a.to_pickle('./data/volL1a.pkl')

volL2a = mf.pivot(index='trade_dt', columns='s_info_windcode', values='sell_volume_large_order_act')
old_volL2a = pd.read_pickle('./data/volL2a.pkl')
volL2a = pd.concat([old_volL2a, volL2a], axis=0)
volL2a = volL2a.reindex(columns=listdays.columns)
volL2a.to_pickle('./data/volL2a.pkl')

# 更新停牌

In [15]:
is_suspend = amount==0
is_suspend.to_pickle('./data/is_suspend.pkl')

# 更新行业分类

In [16]:
old_indint = pd.read_pickle('./data/indint.pkl')
indint = pd.read_pickle('./data_update/indint.pkl')
indint = pd.concat([old_indint, indint], axis=0).reindex(columns=listdays.columns).fillna(-1).astype(int)
indint.to_pickle('./data/indint.pkl')
indint

code,000004.SZ,000005.SZ,600652.SH,600656.SH,600602.SH,600601.SH,600654.SH,600651.SH,600653.SH,000002.SZ,...,603293.SH,301513.SZ,920191.BJ,688820.SH,001312.SZ,688808.SH,920125.BJ,920156.BJ,920186.BJ,301599.SZ
20140102,17,22,1,12,24,26,24,15,12,22,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
20140103,17,22,1,12,24,26,24,15,12,22,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
20140106,17,22,1,12,24,26,24,15,12,22,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
20140107,17,22,1,12,24,26,24,15,12,22,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
20140108,17,22,1,12,24,26,24,15,12,22,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20260424,26,3,27,12,26,26,26,15,12,22,...,12,9,-1,24,16,9,-1,-1,-1,9
20260427,26,3,27,12,26,26,26,15,12,22,...,12,9,-1,24,16,9,-1,-1,-1,9
20260428,26,3,27,12,26,26,26,15,12,22,...,12,9,-1,24,16,9,-1,-1,-1,9
20260429,26,3,27,12,26,26,26,15,12,22,...,12,9,-1,24,16,9,-1,-1,-1,9
20260430,26,3,27,12,26,26,26,15,12,22,...,12,9,-1,24,16,9,-1,-1,-1,9

# 更新barra

In [17]:
# factors = pd.read_pickle('./data_update/factors.pkl')

# liq = factors.pivot(index='trade_date', columns='code', values='liq')
# old_liq = pd.read_pickle('./data/liq.pkl')
# liq = pd.concat([old_liq, liq], axis=0)
# liq = liq.reindex(columns=listdays.columns)
# liq.sort_index().to_pickle('./data/liq.pkl')

# nlsize = factors.pivot(index='trade_date', columns='code', values='nlsize')
# old_nlsize = pd.read_pickle('./data/nlsize.pkl')
# nlsize = pd.concat([old_nlsize, nlsize], axis=0)
# nlsize = nlsize.reindex(columns=listdays.columns)
# nlsize.sort_index().to_pickle('./data/nlsize.pkl')

# size = factors.pivot(index='trade_date', columns='code', values='size')
# old_size = pd.read_pickle('./data/size.pkl')
# size = pd.concat([old_size, size], axis=0)
# size = size.reindex(columns=listdays.columns)
# size.sort_index().to_pickle('./data/size.pkl')

# beta = factors.pivot(index='trade_date', columns='code', values='beta')
# old_beta = pd.read_pickle('./data/beta.pkl')
# beta = pd.concat([old_beta, beta], axis=0)
# beta = beta.reindex(columns=listdays.columns)
# beta.sort_index().to_pickle('./data/beta.pkl')

# resvol = factors.pivot(index='trade_date', columns='code', values='resvol')
# old_resvol = pd.read_pickle('./data/resvol.pkl')
# resvol = pd.concat([old_resvol, resvol], axis=0)
# resvol = resvol.reindex(columns=listdays.columns)
# resvol.sort_index().to_pickle('./data/resvol.pkl')

# mom = factors.pivot(index='trade_date', columns='code', values='mom')
# old_mom = pd.read_pickle('./data/mom.pkl')
# mom = pd.concat([old_mom, mom], axis=0)
# mom = mom.reindex(columns=listdays.columns)
# mom.sort_index().to_pickle('./data/mom.pkl')

# # 20日反转
# returns = pd.read_pickle('./data/returns.pkl')
# ret20 = returns.rolling(20).sum()
# ret20.to_pickle('./data/ret20.pkl')

# 更新市场指数

In [18]:
mkt = pd.read_pickle('./data_update/mkt.pkl')
index_list = {'zzqz': '000985.CSI', 'sz50': '000016.SH', 'hs300': '000300.SH', 'zz500': '000905.SH', 'zz1000': '000852.SH'}
for inst in index_list.keys():
    df = mkt[mkt['code']==index_list[inst]].sort_values('trade_date').set_index('trade_date')
    old_df = pd.read_pickle(f'./data/{inst}.pkl')
    df = pd.concat([old_df, df], axis=0)
    df.to_pickle(f'./data/{inst}.pkl')

# 更新港股

In [19]:
old_calendar_hk = pd.read_pickle('./data/calendar_hk.pkl')
new_calendar_hk = pd.read_pickle('./data_update/calendar_hk.pkl')
calendar_hk = pd.concat([old_calendar_hk, new_calendar_hk]).reset_index(drop=True)
calendar_hk.to_pickle('./data/calendar_hk.pkl')

In [20]:
index_list = {'hsi': 'HSI.HI', 'hstech': 'HSTECH.HI'}
hkmkt = pd.read_pickle('./data_update/hkmkt.pkl')
for inst in index_list.keys():
    hk = hkmkt[hkmkt['code']==index_list.get(inst)]
    old_hk = pd.read_pickle(f'./data/{inst}.pkl')
    hk = pd.concat([old_hk, hk], axis=0)
    hk.to_pickle(f'./data/{inst}.pkl')

# 更新指数成份信息

In [ ]:
pd.set_option('future.no_silent_downcasting', True)
codes = {'zz1000': '000852.SH', 'zzqz': '000985.CSI', 'zz500': '000905.SH', 'hs300': '000300.SH', 'zz2000': '932000.CSI'}
keys = list(codes.keys()); values = list(codes.values())
mb_info = pd.read_pickle('./data_update/mb_info.pkl')
for key in keys:
    new_is_mb = pd.DataFrame(False, index=new_calendar.values, columns=listdays.columns)
    mb_info2 = mb_info.query('s_info_windcode==@codes[@key]', engine='python')
    for name, row in mb_info2.iterrows():
        new_is_mb.loc[(new_is_mb.index>=row['s_con_indate'])&(new_is_mb.index<=row['s_con_outdate']), row['s_con_windcode']] = True
    old_is_mb = pd.read_pickle(f'./data/mb_{key}.pkl')
    is_mb = pd.concat([old_is_mb, new_is_mb]).fillna(False).astype(bool)
    is_mb.to_pickle(f'./data/mb_{key}.pkl')

C:\Users\YxyLO\AppData\Local\Temp\ipykernel_28752\2901455934.py:10: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  is_mb = pd.concat([old_is_mb, new_is_mb]).fillna(False).astype(bool)
C:\Users\YxyLO\AppData\Local\Temp\ipykernel_28752\2901455934.py:10: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  is_mb = pd.concat([old_is_mb, new_is_mb]).fillna(False).astype(bool)
C:\Users\YxyLO\AppData\Local\Temp\ipykernel_28752\2901455934.py:10: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  is_mb = pd.concat([old_is_mb, new_is_mb]).fillna(False).astype(bool)
C:\Users\YxyLO\AppData\Local\Temp\ipykernel_28752\2901455934.py:10: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  is_mb = pd.concat([old_is_mb, new_is_mb]).fillna(False).astype(bool)
C:\Users\YxyLO\AppData\Local\Temp\ipykernel_28752\2901455934.py:10: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  is_mb = pd.concat([old_is_mb, new_is_mb]).fillna(False).astype(bool)